
@echo off

REM !!! Generated by the fmp-cli 1.33.0.  DO NOT EDIT!

md DrugFace\Assets\3rd\fmp-xtc-drugface

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-drugface-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\DrugFace\Assets\3rd\fmp-xtc-drugface\
